-- Script de Base de Datos Oracle
-- Sistema de Gestion de Laboratorios y Resultados

-- Crear usuario (ejecutar solo si es necesario)
-- CREATE USER backend IDENTIFIED BY backend123;
-- GRANT CONNECT, RESOURCE, DBA TO backend;
-- GRANT UNLIMITED TABLESPACE TO backend;

-- Limpieza de tablas existentes

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE RESULTS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USER_ROLES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ROLES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE LABS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Eliminar secuencias existentes
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE ROLES_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE USERS_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE LABS_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE RESULTS_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Creacion de tablas

-- Tabla ROLES
CREATE TABLE ROLES (
    ID NUMBER(19) PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL
);

-- Tabla USERS
CREATE TABLE USERS (
    ID NUMBER(19) PRIMARY KEY,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    FULL_NAME VARCHAR2(150) NOT NULL
);

-- Tabla USER_ROLES (relación ManyToMany)
CREATE TABLE USER_ROLES (
    USER_ID NUMBER(19) NOT NULL,
    ROLE_ID NUMBER(19) NOT NULL,
    PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_USER_ROLES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_USER_ROLES_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE CASCADE
);

-- Tabla LABS
CREATE TABLE LABS (
    ID NUMBER(19) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL
);

-- Tabla RESULTS
CREATE TABLE RESULTS (
    ID NUMBER(19) PRIMARY KEY,
    USER_ID NUMBER(19) NOT NULL,
    LAB_ID NUMBER(19) NOT NULL,
    TEST_TYPE VARCHAR2(100),
    VALUE_JSON CLOB,
    STATUS VARCHAR2(50),
    RESULT_DATE DATE,
    CONSTRAINT FK_RESULTS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    CONSTRAINT FK_RESULTS_LAB FOREIGN KEY (LAB_ID) REFERENCES LABS(ID) ON DELETE CASCADE
);

-- Creacion de secuencias

CREATE SEQUENCE ROLES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LABS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RESULTS_SEQ START WITH 1 INCREMENT BY 1;

-- Datos de prueba

-- Insertar Roles (mínimo 3)
INSERT INTO ROLES (ID, NAME) VALUES (ROLES_SEQ.NEXTVAL, 'ADMINISTRADOR');
INSERT INTO ROLES (ID, NAME) VALUES (ROLES_SEQ.NEXTVAL, 'MEDICO');
INSERT INTO ROLES (ID, NAME) VALUES (ROLES_SEQ.NEXTVAL, 'PACIENTE');
INSERT INTO ROLES (ID, NAME) VALUES (ROLES_SEQ.NEXTVAL, 'LABORATORISTA');

-- Insertar Usuarios (mínimo 3)
-- Passwords BCrypt (para pruebas de login):
--   admin@laboratorio.cl     → admin123
--   doctor@laboratorio.cl    → doctor123
--   paciente@laboratorio.cl  → paciente123
--   lab@laboratorio.cl       → lab123

INSERT INTO USERS (ID, EMAIL, PASSWORD_HASH, FULL_NAME)
VALUES (USERS_SEQ.NEXTVAL, 'admin@laboratorio.cl',
'$2a$10$N9qo8uLOickgx2ZMRZoMye1J5T7A8Q8NtJ0xH0iJ6P4/UXC0jL.2q',
'Juan Pérez Administrador');

INSERT INTO USERS (ID, EMAIL, PASSWORD_HASH, FULL_NAME)
VALUES (USERS_SEQ.NEXTVAL, 'doctor@laboratorio.cl',
'$2a$10$8rByHBczC/nR6gL/HQCFEO0r3L0mz8OdLF.EK.zQvBm7Kg0Ql7Y6m',
'María González Médico');

INSERT INTO USERS (ID, EMAIL, PASSWORD_HASH, FULL_NAME)
VALUES (USERS_SEQ.NEXTVAL, 'paciente@laboratorio.cl',
'$2a$10$F0YQGNuB8k7nMU/rI/6nUeYfR.c3N6xYx6M7/z7qz5F5F5F5F5F5a',
'Carlos Rodríguez Paciente');

INSERT INTO USERS (ID, EMAIL, PASSWORD_HASH, FULL_NAME)
VALUES (USERS_SEQ.NEXTVAL, 'lab@laboratorio.cl',
'$2a$10$F0YQGNuB8k7nMU/rI/6nUeYfR.c3N6xYx6M7/z7qz5F5F5F5F5F5b',
'Ana Martínez Laboratorista');

-- Asignar Roles a Usuarios
-- Usuario 1 (admin) - ADMINISTRADOR
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);

-- Usuario 2 (doctor) - MEDICO
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (2, 2);

-- Usuario 3 (paciente) - PACIENTE
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (3, 3);

-- Usuario 4 (laboratorista) - LABORATORISTA
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (4, 4);

-- Usuario 2 también es ADMINISTRADOR (ejemplo de múltiples roles)
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES (2, 1);

-- Insertar Laboratorios (mínimo 3)
INSERT INTO LABS (ID, NAME) VALUES (LABS_SEQ.NEXTVAL, 'Laboratorio Central Santiago');
INSERT INTO LABS (ID, NAME) VALUES (LABS_SEQ.NEXTVAL, 'Laboratorio Clínico Viña del Mar');
INSERT INTO LABS (ID, NAME) VALUES (LABS_SEQ.NEXTVAL, 'Laboratorio de Análisis Concepción');
INSERT INTO LABS (ID, NAME) VALUES (LABS_SEQ.NEXTVAL, 'Laboratorio Especializado La Serena');

-- Insertar Resultados (mínimo 3)
INSERT INTO RESULTS (ID, USER_ID, LAB_ID, TEST_TYPE, VALUE_JSON, STATUS, RESULT_DATE)
VALUES (RESULTS_SEQ.NEXTVAL, 3, 1, 'Hemograma Completo',
'{"hemoglobina": 14.5, "hematocrito": 42, "leucocitos": 7500}',
'COMPLETADO', TO_DATE('2025-01-15', 'YYYY-MM-DD'));

INSERT INTO RESULTS (ID, USER_ID, LAB_ID, TEST_TYPE, VALUE_JSON, STATUS, RESULT_DATE)
VALUES (RESULTS_SEQ.NEXTVAL, 3, 2, 'Perfil Lipídico',
'{"colesterol_total": 180, "hdl": 55, "ldl": 110, "trigliceridos": 95}',
'COMPLETADO', TO_DATE('2025-01-20', 'YYYY-MM-DD'));

INSERT INTO RESULTS (ID, USER_ID, LAB_ID, TEST_TYPE, VALUE_JSON, STATUS, RESULT_DATE)
VALUES (RESULTS_SEQ.NEXTVAL, 2, 1, 'Glicemia en Ayunas',
'{"glucosa": 92}',
'COMPLETADO', TO_DATE('2025-01-22', 'YYYY-MM-DD'));

INSERT INTO RESULTS (ID, USER_ID, LAB_ID, TEST_TYPE, VALUE_JSON, STATUS, RESULT_DATE)
VALUES (RESULTS_SEQ.NEXTVAL, 3, 3, 'Función Renal',
'{"creatinina": 0.9, "urea": 28, "acido_urico": 5.2}',
'EN_PROCESO', TO_DATE('2025-01-25', 'YYYY-MM-DD'));

INSERT INTO RESULTS (ID, USER_ID, LAB_ID, TEST_TYPE, VALUE_JSON, STATUS, RESULT_DATE)
VALUES (RESULTS_SEQ.NEXTVAL, 4, 2, 'Prueba de COVID-19',
'{"resultado": "negativo", "metodo": "PCR"}',
'COMPLETADO', TO_DATE('2025-01-28', 'YYYY-MM-DD'));

-- Confirmar cambios
COMMIT;

-- Verificacion de datos

SELECT 'ROLES: ' || COUNT(*) || ' registros' AS VERIFICACION FROM ROLES;
SELECT 'USERS: ' || COUNT(*) || ' registros' AS VERIFICACION FROM USERS;
SELECT 'USER_ROLES: ' || COUNT(*) || ' registros' AS VERIFICACION FROM USER_ROLES;
SELECT 'LABS: ' || COUNT(*) || ' registros' AS VERIFICACION FROM LABS;
SELECT 'RESULTS: ' || COUNT(*) || ' registros' AS VERIFICACION FROM RESULTS;

-- Mostrar contenido de las tablas
SELECT * FROM ROLES;
SELECT * FROM USERS;
SELECT * FROM USER_ROLES;
SELECT * FROM LABS;
SELECT * FROM RESULTS;
